### ISSUE TITLE
Can't set a doctrine Embedded object money type with the MoneyType Form

### ISSUE THREAD

**Issue by BungETH** [yceruto/money-bundle#9] opened 2023-01-12 11:33 UTC
Given this property in my entity :

`#[ORM\Embedded]`
  `private Money $minDeposit;`

with this getters and setters : 

```  
 /**
     * @return Money
     */
    public function getMinDeposit(): Money
    {
        return $this->minDeposit;
    }

    /**
     * @param Money $minDeposit
     * @return Caisse
     */
    public function setMinDeposit(Money $minDeposit): Caisse
    {
        $this->minDeposit = $minDeposit;
        return $this;
    } 
```
i've created a form for this field  with this options : 

```        
$builder
            ->add('title', TextType::class)
            ->add('description', TextareaType::class)
            ->add('iban', TextType::class)
            ->add('minDeposit', MoneyType::class)
            ->add('submit', SubmitType::class)
        ;
```

When the form is submit i've got this error :  `Expected argument of type "Money\Money", "float" given at property path "minDeposit".`

Did i miss something ?

**Comment by yceruto** [comment] 2023-01-12 14:49
The Symfony `MoneyType` is not compatible with `Money\Money` objects. It requires a numeric value instead, as stated in the error message. Additionally, the `Money\Money` object is immutable, so the Form component cannot modify its value without a custom mapping.

This bundle only modifies the `MoneyType` to properly handle the `currency` option and automatically sets the correct values for `scale` and `divisor`. However, it still expects a single numeric property as input, as it is a single-form field rather than a compound field.

You can see an example of its intended usage here:
https://github.com/yceruto/money-bundle/blob/70722dc0f3af2c38b25d8bb88a8747011d1982db/tests/Form/Type/MoneyTypeTest.php#L122

Now, to make it works with your case, you have some options:
 *  Use DTO instead of Entity, so you can provide a `string|int` amount property for `MoneyType` (preferred option)
 * Add a custom data mapping as documented here https://symfony.com/doc/current/form/data_mappers.html#mapping-form-fields-using-callbacks

### Here is a sample using a custom data mapper

Given a `Product` entity with `name` and `price` properties, where `price` must be an instance of `Money\Money`:

```php
class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('name');

        $builder->addEventListener(FormEvents::PRE_SET_DATA, static function (FormEvent $event) {
            /** @var Product $product */
            $product = $event->getData();
            $form = $event->getForm();

            $form->add('price', MoneyType::class, [
                'currency' => $product->getPrice()->getCurrency()->getCode(),
                'getter' => static function (Product $product) {
                    return $product->getPrice()->getAmount();
                },
                'setter' => static function (Product $product, string $amount) {
                    $product->setPrice(new Money($amount, $product->getPrice()->getCurrency()));
                },
            ]);
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}
```
---
Closing as this is not a bug.

**Closed as completed by yceruto** 2023-01-12 14:49 UTC

**Comment by BungETH** [comment] 2023-01-12 17:28
Thx for the response and the advices !
