### ISSUE TITLE
Impossible to use custom Formatter to all currencies

### ISSUE THREAD

**Issue by ais8xl** [yceruto/money-bundle#15] opened 2024-08-25 15:19 UTC
Currently is impossible to use custom Formatter to all currencies as described in the documentation.

I have done the next:

Custom formatter:
```
<?php

namespace App\Money;

use Money\Money;
use \Money\MoneyFormatter as MoneyFormatterInterface;

class CustomFormatter implements MoneyFormatterInterface
{
    public function format(Money $money): string
    {
        return number_format(
            num: $money->getAmount() / 10 ** 3,
            decimals: 3,
            thousands_separator: ' ',
        );
    }
}
```

services.yaml:
```
App\Money\CustomFormatter:
        tags:
            - { name: money.formatter, code: '*' }
```

result after dd:
```
array:3 [▼
  "*" => Money\Formatter\IntlMoneyFormatter {#12276 ▶}
  "App\Money\CustomFormatter" => App\Money\CustomFormatter {#18531}
  "XBT" => Money\Formatter\BitcoinMoneyFormatter {#18061 ▶}
]
```

Why also something is parsing the classes that implemented your interface and pushed it also to the `$this->formatters` of the class `AggregateMoneyFormatter`? IMHO This is unnecessary

**Comment by yceruto** [comment] 2024-08-25 22:48
Money formatters are indexed by currency `code`. When there are multiple formatters associated to the same currency `code`, in this case `*`, the last one registered will win, and that's the case when you register a new formatter in your app (unless you set a priority attribute directly).
```
array:3 [▼
  "*" => Money\Formatter\IntlMoneyFormatter {#12276 ▶}
  "App\Money\CustomFormatter" => App\Money\CustomFormatter {#18531}
  "XBT" => Money\Formatter\BitcoinMoneyFormatter {#18061 ▶}
]
```
That dd output makes me think you might have forgotten to import the `services.yaml` file, or for some unknown reason it's not taken into account (maybe the extra indentation of the `tags` line), because the index can't be `"App\Money\CustomFormatter"`.

**Comment by yceruto** [comment] 2024-08-25 22:49
Closing this as a misconfiguration. Thanks for reporting anyway.

**Closed as completed by yceruto** 2024-08-25 22:49 UTC

**Comment by ais8xl** [comment] 2024-08-26 05:27
@yceruto services.yaml is imported, and if it looks like this:
```
App\Money\CustomFormatter:
        tags:
            - { name: money.formatter, code: 'EUR' }
```
Then dd output is:
```
array:3 [▼
  "EUR" => App\Money\CustomFormatter {#18531}
  "*" => Money\Formatter\IntlMoneyFormatter {#12276 ▶}
  "App\Money\CustomFormatter" => App\Money\CustomFormatter {#18531}
  "XBT" => Money\Formatter\BitcoinMoneyFormatter {#18061 ▶}
]
```

**Comment by yceruto** [comment] 2024-08-26 12:23
I can't reproduce your issue on my side, it looks like your custom formatter is registered twice (one of them without tag).

Try using priority to see what happen:
```yaml
App\Money\CustomFormatter:
    tags:
        - { name: money.formatter, code: '*', priority: -1 }
```

**Comment by yceruto** [comment] 2024-08-26 12:24
otherwise I would need a test case failing on this repo or a small app reproducing your issue.
